
package Screens;

import ConnectSQL.ConnectDAO;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class AlterarDados extends javax.swing.JFrame {

    static int idUser;
    
    public AlterarDados(int novoId) {
        initComponents();
        setIcon();
        idUser = novoId;
        
        campoSenha.setEchoChar('\u25cf');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarDados = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        campoEmail = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JLabel();
        esconder = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alterarDados.setContentAreaFilled(false);
        alterarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(alterarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 360, 60));

        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 41, 90, 80));

        campoEmail.setBackground(new java.awt.Color(255, 255, 255));
        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoEmail.setBorder(null);
        getContentPane().add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 389, 920, 50));

        campoNome.setBackground(new java.awt.Color(255, 255, 255));
        campoNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoNome.setBorder(null);
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 244, 920, 50));

        campoSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(0, 0, 0));
        campoSenha.setBorder(null);
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 534, 880, 50));

        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mostrar.png"))); // NOI18N
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 540, 40, 40));

        esconder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/esconder.png"))); // NOI18N
        esconder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esconder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esconderMouseClicked(evt);
            }
        });
        getContentPane().add(esconder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 540, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar dados da conta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosActionPerformed
        // botao alterar dados 
       
         try {
    
            if(campoNome.getText().length() == 0 && campoEmail.getText().length() == 0 &&  new String (campoSenha.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(null, "Erro: Todos os campos estão vazios!");
            return; 
            }

            if(campoNome.getText().length() != 0) new ConnectDAO().AlterName(idUser, campoNome.getText());
            if(campoEmail.getText().length() != 0) new ConnectDAO().AlterEmail(idUser, campoEmail.getText());
            if( new String (campoSenha.getPassword()).length() != 0) new ConnectDAO().AlterSenha(idUser, new String (campoSenha.getPassword()));

    
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
            new Login().setVisible(true);
            dispose();
            
            } catch (HeadlessException e) {
    
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao alterar os dados: " + e.getMessage());
            }

    }//GEN-LAST:event_alterarDadosActionPerformed

    private void esconderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esconderMouseClicked
        // TODO add your handling code here:

        mostrar.setVisible(true);
        esconder.setVisible(false);
        campoSenha.setEchoChar('\u25cf');
    }//GEN-LAST:event_esconderMouseClicked

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked
        // TODO add your handling code here:

        mostrar.setVisible(false);
        esconder.setVisible(true);
        campoSenha.setEchoChar((char)0);
    }//GEN-LAST:event_mostrarMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        
        new MinhaConta(idUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AlterarDados(idUser).setVisible(true);
        });/* {
        */
    }
    
    private void setIcon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LogoIcon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarDados;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel esconder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mostrar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
