
package Screens;

import ConnectSQL.ConnectDAO;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class CriarCards extends javax.swing.JFrame {

    static int idUser, idList;
    
    
    public CriarCards(int novoIdList, int novoId, String nomeFlashcards) {
        initComponents();
        setIcon();
        idList = novoIdList;
        idUser = novoId;
        this.jLabel2.setText(nomeFlashcards);
        campoPergunta.setWrapStyleWord(true);
        campoResposta.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvarLista = new javax.swing.JButton();
        adicionarCard = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoResposta = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoPergunta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarLista.setContentAreaFilled(false);
        salvarLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarListaActionPerformed(evt);
            }
        });
        getContentPane().add(salvarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 620, 270, 60));

        adicionarCard.setContentAreaFilled(false);
        adicionarCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCardActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 270, 60));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        campoResposta.setBackground(new java.awt.Color(241, 239, 246));
        campoResposta.setColumns(20);
        campoResposta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        campoResposta.setLineWrap(true);
        campoResposta.setRows(5);
        campoResposta.setBorder(null);
        jScrollPane2.setViewportView(campoResposta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 394, 810, 180));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setRowHeaderView(null);

        campoPergunta.setBackground(new java.awt.Color(241, 239, 246));
        campoPergunta.setColumns(20);
        campoPergunta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        campoPergunta.setLineWrap(true);
        campoPergunta.setRows(5);
        campoPergunta.setBorder(null);
        jScrollPane1.setViewportView(campoPergunta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 212, 810, 110));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 104, 720, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Criar cards.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCardActionPerformed
        // botao Criar Lista

       if(campoPergunta.getText().length() != 0 && campoResposta.getText().length() != 0){
           try{
           new ConnectDAO().InsertAskAnswer(campoPergunta.getText(), campoResposta.getText(), idList, idUser);
           }catch(SQLException sql){
           }
       }else{
           JOptionPane.showMessageDialog(null, "campos vazios", "aviso!", 2);
       }
        campoPergunta.setText("");
        campoResposta.setText("");
            
    }//GEN-LAST:event_adicionarCardActionPerformed

    private void salvarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarListaActionPerformed
        // botao salvar Lista
        
        if(campoPergunta.getText().length() != 0 && campoResposta.getText().length() != 0){
            try{
            new ConnectDAO().InsertAskAnswer(campoPergunta.getText(), campoResposta.getText(), idList, idUser);
            }catch(SQLException ei){
            }
           new MeusFlashcards(idUser).setVisible(true);
           dispose();
        }else{
           new MeusFlashcards(idUser).setVisible(true);
           dispose();
       }
        

        // new ConnectDAO().CreateTable(campoNome.getText());
        // campoNome.setText("");
    }//GEN-LAST:event_salvarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarCards(idList, idUser, null).setVisible(true);
            }
        });
    }

    private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LogoIcon.png")));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCard;
    private javax.swing.JTextArea campoPergunta;
    private javax.swing.JTextArea campoResposta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salvarLista;
    // End of variables declaration//GEN-END:variables
}
